### PR TITLE
Milestone #2

### PR DESCRIPTION
**Pull request by upluke**
# Milestone: {Milestone #2}
# Developer: {Ke Lyu}

### Pull Request Summary
All challenges are done.

{Describe the purpose of your pull request}

### Pull Request Checklist
- [ x] Code is neat, readable, and works
- [ x] Comments are appropriate
- [ x] The commit message follows our guidelines
- [ x] The milestone number is specified
- [ x] The developer name is specified
- [ x] The summary is completed

### Reviewer Checklist  - PULL REQUEST REVIEWER ONLY

IMPORTANT: The rest of the sections in this checklist should only be filled out by authorized pull request reviewers. If you are the individual template contributor, do not fill out the rest of the fields or check the boxes.

NOTE: Milestones can only be completed when all boxes are checked.

- [ ] The code is fully reviewed
- [ ] Meaningful feedback is given
- [ ] Comment that you have reviewed the code
- [ ] This box is checked

### CODE REVIEW

**Review by vwinstea — COMMENTED** [review]
Your code is looking good, but I'm curious what all these extra files are. Could you tell me what issue you were running into here?

**Comment by upluke** [comment]
> 
Hi, what do you mean by extra files?

**Comment by vwinstea** [comment]
If you look at the files you committed, there's the modified milestone2.ts, but there's also four new files: milestone2.js, tests/data.js, tests/milestone2.test.js, tests/solutions.js . Do you know what would've created the new files?

**Comment by vwinstea** [comment]
Milestone 2 complete!

**Pull request closed without merging**
